name:新闻抓取推送任务
on:
  schedule:
    # UTC时区！北京时间早上8点推送 = UTC 0点
    - cron: '0 0 * * *'
  workflow_dispatch: # 支持手动点击测试运行

jobs:
  crawl_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 安装依赖库
        run: pip3 install requests beautifulsoup4
      - name: 执行新闻抓取脚本
        run: python3 crawl.py
